FROM python:3.9
COPY authorization_test.py .
RUN apt-get update && apt-get install -y apt-utils && apt-get upgrade -y && apt-get install -y python3-pip
RUN pip3 install requests
#EXPOSE 8000
RUN python3 authorization_test.py