FROM python:3.9
ADD authentication_test.py . 
RUN apt-get update && apt-get install -y apt-utils && apt-get upgrade -y && apt-get install -y python3-pip
EXPOSE 8000
RUN pip install requests
RUN python3 authentication_test.py